<a href="https://colab.research.google.com/github/MUMADE-TADM/s1_python-gercevas/blob/main/TADM2022_S03b_Consultas_SQL_(Clase).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Consultas SQL


Antes de empezar cargamos nuestro archivo data_berka en nuestro entorno: [enlace](https://sorry.vse.cz/~berka/challenge/pkdd1999/berka.htm)

In [ ]:
!gdown --id 1Osmr7qVN0NMuqYxvLesNn7H4nqPCVbsU

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1Osmr7qVN0NMuqYxvLesNn7H4nqPCVbsU
To: /content/data_berka.db
100% 70.2M/70.2M [00:00<00:00, 143MB/s]

En primer lugar cargamos la extensión que nos va permitir manejar comandos sql directamente en colab

In [ ]:
%load_ext sql

Y conectamos con la base de datos

In [ ]:
%sql sqlite:///data_berka.db

'Connected: @data_berka.db'

Comprobamos esquema

In [ ]:
%%sql
SELECT name,type
FROM sqlite_master
WHERE type = 'table'

 * sqlite:///data_berka.db
Done.

[('DISTRICT', 'table'),
 ('ACCOUNT', 'table'),
 ('TRANS', 'table'),
 ('CLIENT', 'table'),
 ('DISPOSITION', 'table'),
 ('CREDIT_CARD', 'table'),
 ('LOAN', 'table'),
 ('PERMANENT_ORDER', 'table')]

## Consultas sobre Préstamos

1. Obtener todos los atributos que tiene el banco sobre sus préstamos.

(extra limitar a 20 registros)

In [ ]:
%%sql
SELECT *
FROM LOAN
LIMIT 20

 * sqlite:///data_berka.db
Done.

[(5314, 1787, 930705, 96396, 12, 8033, 'B'),
 (5316, 1801, 930711, 165960, 36, 4610, 'A'),
 (6863, 9188, 930728, 127080, 60, 2118, 'A'),
 (5325, 1843, 930803, 105804, 36, 2939, 'A'),
 (7240, 11013, 930906, 274740, 60, 4579, 'A'),
 (6687, 8261, 930913, 87840, 24, 3660, 'A'),
 (7284, 11265, 930915, 52788, 12, 4399, 'A'),
 (6111, 5428, 930924, 174744, 24, 7281, 'B'),
 (7235, 10973, 931013, 154416, 48, 3217, 'A'),
 (5997, 4894, 931104, 117024, 24, 4876, 'A'),
 (7121, 10364, 931110, 21924, 36, 609, 'A'),
 (6077, 5270, 931122, 79608, 24, 3317, 'A'),
 (6228, 6034, 931201, 464520, 60, 7742, 'B'),
 (6356, 6701, 931208, 95400, 36, 2650, 'A'),
 (5523, 2705, 931208, 93888, 36, 2608, 'A'),
 (6456, 7123, 931209, 47016, 12, 3918, 'A'),
 (7104, 10320, 931213, 259740, 60, 4329, 'A'),
 (6820, 9034, 931216, 38148, 12, 3179, 'A'),
 (6876, 9236, 931221, 86616, 12, 7218, 'A'),
 (7097, 10266, 931223, 75624, 24, 3151, 'B')]

2. Obtener los campos de fecha (date), cantidad (amount), duración (duration), pagos (payments), estado (status)

(extra limitar a 20 registros)

In [ ]:
%%sql
SELECT date, amount, duration, payments, status
FROM LOAN
ORDER BY amount DESC
LIMIT 20

 * sqlite:///data_berka.db
Done.

[(971019, 590820, 60, 9847, 'C'),
 (980123, 566640, 60, 9444, 'C'),
 (971112, 541200, 60, 9020, 'D'),
 (950217, 538500, 60, 8975, 'C'),
 (980120, 504000, 60, 8400, 'C'),
 (980522, 495180, 60, 8253, 'C'),
 (941219, 482940, 60, 8049, 'D'),
 (970212, 475680, 48, 9910, 'C'),
 (970907, 473280, 60, 7888, 'D'),
 (971225, 468060, 60, 7801, 'C'),
 (970613, 466608, 48, 9721, 'C'),
 (971227, 465504, 48, 9698, 'D'),
 (950709, 465072, 48, 9689, 'C'),
 (931201, 464520, 60, 7742, 'B'),
 (971105, 460980, 60, 7683, 'D'),
 (960723, 444864, 48, 9268, 'C'),
 (980829, 437460, 60, 7291, 'C'),
 (980213, 428784, 48, 8933, 'C'),
 (961118, 421008, 48, 8771, 'C'),
 (951029, 419880, 60, 6998, 'C')]

3. Obtener los distintos tipos de estado que se presentan en un préstamo.

In [ ]:
%%sql
SELECT DISTINCT status
FROM LOAN
ORDER BY status

 * sqlite:///data_berka.db
Done.

[('A',), ('B',), ('C',), ('D',)]

4. Obtener solo los prestamos ya terminados. Ordenar lo anterior por duración y cantidad

In [ ]:
%%sql
SELECT *
FROM LOAN
WHERE status in ("A", "B")
ORDER BY duration, amount DESC
LIMIT 100

 * sqlite:///data_berka.db
Done.

[(6934, 9494, 970209, 116832, 12, 9736, 'A'),
 (5002, 173, 940531, 104808, 12, 8734, 'A'),
 (4986, 97, 970810, 102876, 12, 8573, 'A'),
 (5375, 2106, 961003, 101520, 12, 8460, 'A'),
 (7253, 11079, 970426, 98304, 12, 8192, 'A'),
 (6998, 9833, 940521, 97632, 12, 8136, 'A'),
 (6612, 7907, 970831, 97392, 12, 8116, 'A'),
 (5314, 1787, 930705, 96396, 12, 8033, 'B'),
 (6995, 9814, 960926, 96168, 12, 8014, 'A'),
 (5464, 2419, 950130, 95808, 12, 7984, 'A'),
 (5643, 3273, 970921, 94512, 12, 7876, 'B'),
 (5377, 2116, 970804, 92400, 12, 7700, 'A'),
 (5519, 2694, 940308, 91632, 12, 7636, 'A'),
 (7046, 10049, 970328, 91632, 12, 7636, 'A'),
 (5868, 4361, 970329, 90156, 12, 7513, 'A'),
 (7277, 11231, 971024, 89280, 12, 7440, 'A'),
 (4996, 132, 961106, 88440, 12, 7370, 'A'),
 (5882, 4427, 940926, 87816, 12, 7318, 'A'),
 (7119, 10361, 970602, 86880, 12, 7240, 'A'),
 (6876, 9236, 931221, 86616, 12, 7218, 'A'),
 (6921, 9422, 961029, 86184, 12, 7182, 'A'),
 (5366, 2062, 961029, 86184, 12, 7182, 'A'),
 (6150, 5622, 941102, 83016, 12, 6918, 'A'),
 (5595, 3050, 940902, 82896, 12, 6908, 'A'),
 (6678, 8173, 940520, 80340, 12, 6695, 'A'),
 (6059, 5196, 971228, 79824, 12, 6652, 'A'),
 (5285, 1603, 940206, 78936, 12, 6578, 'A'),
 (7051, 10068, 970728, 77808, 12, 6484, 'A'),
 (6642, 8027, 940605, 77640, 12, 6470, 'A'),
 (5117, 718, 970820, 76944, 12, 6412, 'A'),
 (6316, 6473, 940526, 76908, 12, 6409, 'B'),
 (5739, 3747, 950102, 76380, 12, 6365, 'A'),
 (5992, 4863, 970318, 76080, 12, 6340, 'A'),
 (6729, 8519, 940811, 74688, 12, 6224, 'A'),
 (5878, 4415, 970401, 74040, 12, 6170, 'A'),
 (6599, 7859, 961119, 72120, 12, 6010, 'A'),
 (6624, 7965, 940930, 71460, 12, 5955, 'A'),
 (5352, 1993, 950415, 68400, 12, 5700, 'B'),
 (5638, 3249, 970827, 68124, 12, 5677, 'A'),
 (6598, 7857, 950118, 68112, 12, 5676, 'A'),
 (6753, 8688, 970320, 67980, 12, 5665, 'A'),
 (5682, 3455, 970307, 67464, 12, 5622, 'A'),
 (7201, 10807, 970307, 67464, 12, 5622, 'A'),
 (6202, 5891, 940418, 65184, 12, 5432, 'A'),
 (5750, 3804, 960208, 63252, 12, 5271, 'A'),
 (5388, 2153, 961128, 61560, 12, 5130, 'A'),
 (5338, 1888, 970830, 57360, 12, 4780, 'B'),
 (7305, 11359, 960806, 54024, 12, 4502, 'A'),
 (5398, 2187, 971104, 53472, 12, 4456, 'A'),
 (5134, 825, 970202, 53076, 12, 4423, 'A'),
 (7284, 11265, 930915, 52788, 12, 4399, 'A'),
 (5856, 4320, 970809, 51360, 12, 4280, 'B'),
 (6650, 8073, 940217, 49320, 12, 4110, 'B'),
 (6456, 7123, 931209, 47016, 12, 3918, 'A'),
 (7198, 10788, 940823, 45768, 12, 3814, 'A'),
 (7199, 10789, 971209, 45768, 12, 3814, 'A'),
 (7264, 11141, 971007, 44940, 12, 3745, 'A'),
 (6137, 5574, 960410, 44628, 12, 3719, 'A'),
 (6144, 5593, 960809, 44376, 12, 3698, 'A'),
 (6315, 6472, 950206, 43164, 12, 3597, 'A'),
 (6621, 7957, 970614, 42900, 12, 3575, 'A'),
 (6727, 8505, 971210, 42840, 12, 3570, 'A'),
 (6535, 7546, 951102, 41952, 12, 3496, 'A'),
 (6895, 9307, 940919, 41904, 12, 3492, 'A'),
 (6888, 9265, 940711, 39576, 12, 3298, 'A'),
 (6887, 9263, 970508, 39576, 12, 3298, 'A'),
 (5634, 3229, 970501, 39024, 12, 3252, 'A'),
 (5358, 2018, 970121, 38520, 12, 3210, 'A'),
 (6820, 9034, 931216, 38148, 12, 3179, 'A'),
 (6362, 6738, 951031, 37908, 12, 3159, 'A'),
 (6306, 6425, 941220, 36684, 12, 3057, 'A'),
 (6929, 9472, 950508, 36396, 12, 3033, 'A'),
 (7008, 9897, 950922, 36168, 12, 3014, 'A'),
 (6310, 6440, 970617, 34572, 12, 2881, 'A'),
 (5932, 4626, 970618, 33348, 12, 2779, 'A'),
 (6758, 8742, 970729, 33144, 12, 2762, 'A'),
 (5576, 2962, 941221, 31248, 12, 2604, 'A'),
 (6501, 7418, 960429, 30276, 12, 2523, 'B'),
 (4961, 19, 960429, 30276, 12, 2523, 'B'),
 (6502, 7424, 971208, 30276, 12, 2523, 'A'),
 (4962, 25, 971208, 30276, 12, 2523, 'A'),
 (6865, 9199, 960911, 29448, 12, 2454, 'B'),
 (6578, 7765, 951211, 27984, 12, 2332, 'A'),
 (5005, 176, 970410, 27456, 12, 2288, 'A'),
 (5479, 2486, 940110, 24516, 12, 2043, 'A'),
 (5130, 813, 940511, 24312, 12, 2026, 'A'),
 (5723, 3674, 940910, 23628, 12, 1969, 'A'),
 (5229, 1329, 970906, 23520, 12, 1960, 'A'),
 (6878, 9242, 970124, 23184, 12, 1932, 'A'),
 (5754, 3834, 940928, 23052, 12, 1921, 'A'),
 (5980, 4825, 950818, 21396, 12, 1783, 'A'),
 (5922, 4580, 950805, 20220, 12, 1685, 'A'),
 (5651, 3329, 971208, 19248, 12, 1604, 'A'),
 (5740, 3752, 950402, 18564, 12, 1547, 'A'),
 (6942, 9513, 970716, 18324, 12, 1527, 'A'),
 (6297, 6363, 941025, 17508, 12, 1459, 'A'),
 (6377, 6792, 970317, 17184, 12, 1432, 'A'),
 (5599, 3064, 950321, 15420, 12, 1285, 'A'),
 (6064, 5215, 940804, 14628, 12, 1219, 'A'),
 (5718, 3637, 970901, 14028, 12, 1169, 'A')]

Cargar el resultado de la sql en un DataFrame de Pandas

In [ ]:
# importar librería
import pandas as pd
# ejecutar sql
df = %sql SELECT * FROM LOAN WHERE status in ("A", "B") ORDER BY duration, amount DESC
# transformar en DataFrame de pandas y descargarlo en un csv
df.DataFrame().to_csv("first_sql.csv")

 * sqlite:///data_berka.db
Done.

 Ex. 2 

> Seleccionar fecha, cantidad, duración y pagos de aquellos préstamos que han sido terminados con una duración mayor de 12 meses ordenados de mayor a menor cantidad de dinero

In [ ]:
%%sql
SELECT date, amount, duration, payments
FROM LOAN
WHERE status in ("A", "B") AND duration > 12
ORDER BY amount DESC

 * sqlite:///data_berka.db
Done.

[(931201, 464520, 60, 7742),
 (940810, 323472, 48, 6739),
 (940604, 300204, 36, 8339),
 (940730, 299088, 36, 8308),
 (950103, 288468, 36, 8013),
 (940708, 276660, 36, 7685),
 (930906, 274740, 60, 4579),
 (950108, 270648, 36, 7518),
 (950623, 265320, 36, 7370),
 (951028, 260028, 36, 7223),
 (931213, 259740, 60, 4329),
 (950428, 248148, 36, 6893),
 (951020, 231696, 36, 6436),
 (940929, 230220, 36, 6395),
 (941012, 227880, 36, 6330),
 (940825, 224604, 36, 6239),
 (951204, 217152, 36, 6032),
 (940502, 215388, 36, 5983),
 (940331, 212400, 36, 5900),
 (940911, 209184, 48, 4358),
 (940601, 208320, 48, 4340),
 (940724, 208128, 48, 4336),
 (941204, 205200, 36, 5700),
 (950624, 198240, 24, 8260),
 (940223, 197748, 36, 5493),
 (940522, 196080, 48, 4085),
 (940510, 193968, 36, 5388),
 (941003, 192744, 36, 5354),
 (941112, 192552, 24, 8023),
 (940928, 189696, 24, 7904),
 (960101, 189696, 24, 7904),
 (950501, 187224, 24, 7801),
 (960728, 187104, 24, 7796),
 (940301, 182628, 36, 5073),
 (930924, 174744, 24, 7281),
 (940617, 174744, 24, 7281),
 (940711, 173808, 24, 7242),
 (940807, 172080, 48, 3585),
 (941030, 170256, 24, 7094),
 (950304, 168984, 24, 7041),
 (930711, 165960, 36, 4610),
 (960502, 165960, 24, 6915),
 (941119, 164052, 36, 4557),
 (950401, 156672, 36, 4352),
 (960715, 155880, 24, 6495),
 (960804, 155640, 24, 6485),
 (931013, 154416, 48, 3217),
 (940603, 151560, 24, 6315),
 (940207, 149040, 48, 3105),
 (940723, 143904, 24, 5996),
 (960822, 141648, 24, 5902),
 (940930, 141240, 24, 5885),
 (941106, 140400, 36, 3900),
 (950613, 139536, 24, 5814),
 (951128, 137904, 24, 5746),
 (950319, 134784, 24, 5616),
 (940728, 131292, 36, 3647),
 (961227, 129408, 24, 5392),
 (930728, 127080, 60, 2118),
 (950413, 126600, 24, 5275),
 (941103, 123696, 48, 2577),
 (961211, 123408, 24, 5142),
 (940827, 121896, 24, 5079),
 (940805, 120888, 36, 3358),
 (931104, 117024, 24, 4876),
 (941221, 115992, 36, 3222),
 (951122, 113796, 36, 3161),
 (940705, 111384, 24, 4641),
 (961111, 110136, 24, 4589),
 (961109, 110112, 24, 4588),
 (940131, 108144, 36, 3004),
 (950811, 107640, 24, 4485),
 (930803, 105804, 36, 2939),
 (950411, 104712, 24, 4363),
 (951212, 104712, 24, 4363),
 (951104, 99336, 24, 4139),
 (950710, 98592, 24, 4108),
 (941028, 98184, 24, 4091),
 (950223, 97224, 24, 4051),
 (931208, 95400, 36, 2650),
 (931208, 93888, 36, 2608),
 (961020, 93600, 24, 3900),
 (951212, 92976, 24, 3874),
 (940625, 91584, 24, 3816),
 (940316, 91200, 24, 3800),
 (960822, 91152, 24, 3798),
 (960119, 89880, 24, 3745),
 (930913, 87840, 24, 3660),
 (940607, 87360, 24, 3640),
 (940606, 87216, 48, 1817),
 (960922, 84120, 24, 3505),
 (940105, 80952, 24, 3373),
 (940105, 80952, 24, 3373),
 (940827, 79632, 24, 3318),
 (931122, 79608, 24, 3317),
 (950311, 76680, 24, 3195),
 (950111, 76416, 24, 3184),
 (931223, 75624, 24, 3151),
 (940730, 74736, 36, 2076),
 (951031, 73836, 36, 2051),
 (960212, 72408, 24, 3017),
 (950529, 71064, 36, 1974),
 (940612, 69360, 48, 1445),
 (961103, 68544, 24, 2856),
 (960514, 66480, 24, 2770),
 (940526, 63312, 48, 1319),
 (960210, 61656, 24, 2569),
 (941103, 61056, 48, 1272),
 (951112, 60156, 36, 1671),
 (941104, 59760, 24, 2490),
 (940315, 55368, 24, 2307),
 (940604, 52128, 24, 2172),
 (940311, 51696, 24, 2154),
 (941208, 51408, 24, 2142),
 (941106, 48672, 36, 1352),
 (950108, 48624, 24, 2026),
 (950410, 47304, 24, 1971),
 (960629, 46320, 24, 1930),
 (950829, 45336, 24, 1889),
 (950801, 44088, 24, 1837),
 (950327, 31728, 24, 1322),
 (951128, 31176, 24, 1299),
 (950613, 29784, 24, 1241),
 (950304, 28248, 24, 1177),
 (940526, 25944, 24, 1081),
 (931110, 21924, 36, 609),
 (951008, 21852, 36, 607),
 (940121, 21072, 24, 878),
 (960925, 15192, 24, 633),
 (941002, 11736, 24, 489),
 (940330, 7656, 24, 319)]

¿Cuántos registros cumplen esa condición?

In [ ]:
%%sql
SELECT count(*)
FROM LOAN
WHERE status in ("A", "B") AND duration > 12

 * sqlite:///data_berka.db
Done.

[(131,)]

¿Cuántos préstamos hay en ejecución (running) con duración entre 24 y 48 meses

In [ ]:
%%sql
SELECT count(*)
FROM LOAN
WHERE status in ("C", "D") and duration between 24 and 48

 * sqlite:///data_berka.db
Done.

[(279,)]

## Group By

7. ¿Cuántos préstamos hay por cada estado y cual es la media de la cantidad de dinero prestado?

- where: se filtran los registros antes de agruparlos
- having: se filtran los grupos tras obtenerlos

In [ ]:
%%sql
SELECT status, count(*) as total, avg (amount)
FROM LOAN
WHERE duration >= 24
GROUP BY status
HAVING total > 25 
ORDER BY total DESC

 * sqlite:///data_berka.db
Done.

[('C', 376, 180343.1489361702),
 ('A', 110, 122425.2),
 ('D', 44, 254127.27272727274)]

8. Por cada Región, quiero contar el número de ciudades y obtener el total del número de habitantes de la región

extra: no considerar la región de Praga

In [ ]:
%%sql
SELECT * FROM DISTRICT

 * sqlite:///data_berka.db
Done.

[(1, 'Hl.m. Praha', 'Prague', 1204953, 0, 0, 0, 1, 1, 100.0, 12541, 0.29, 0.43, 167, 85677, 99107),
 (2, 'Benesov', 'central Bohemia', 88884, 80, 26, 6, 2, 5, 46.7, 8507, 1.67, 1.85, 132, 2159, 2674),
 (3, 'Beroun', 'central Bohemia', 75232, 55, 26, 4, 1, 5, 41.7, 8980, 1.95, 2.21, 111, 2824, 2813),
 (4, 'Kladno', 'central Bohemia', 149893, 63, 29, 6, 2, 6, 67.4, 9753, 4.64, 5.05, 109, 5244, 5892),
 (5, 'Kolin', 'central Bohemia', 95616, 65, 30, 4, 1, 6, 51.4, 9307, 3.85, 4.43, 118, 2616, 3040),
 (6, 'Kutna Hora', 'central Bohemia', 77963, 60, 23, 4, 2, 4, 51.5, 8546, 2.95, 4.02, 126, 2640, 3120),
 (7, 'Melnik', 'central Bohemia', 94725, 38, 28, 1, 3, 6, 63.4, 9920, 2.26, 2.87, 130, 4289, 4846),
 (8, 'Mlada Boleslav', 'central Bohemia', 112065, 95, 19, 7, 1, 8, 69.4, 11277, 1.25, 1.44, 127, 5179, 4987),
 (9, 'Nymburk', 'central Bohemia', 81344, 61, 23, 4, 2, 6, 55.3, 8899, 3.39, 3.97, 149, 2987, 2487),
 (10, 'Praha - vychod', 'central Bohemia', 92084, 55, 29, 4, 3, 5, 46.7, 10124, 0.56, 0.54, 141, 3810, 4316),
 (11, 'Praha - zapad', 'central Bohemia', 75637, 35, 36, 9, 0, 7, 36.5, 9622, 0.45, 0.59, 154, 3475, 3529),
 (12, 'Pribram', 'central Bohemia', 107870, 84, 29, 6, 1, 6, 58.0, 8754, 3.83, 4.31, 137, 3804, 3868),
 (13, 'Rakovnik', 'central Bohemia', 53921, 61, 22, 1, 1, 2, 41.3, 8598, 2.77, 3.26, 123, 1597, 1875),
 (14, 'Ceske Budejovice', 'south Bohemia', 177686, 69, 27, 10, 1, 9, 74.8, 10045, 1.42, 1.71, 135, 6604, 6295),
 (15, 'Cesky Krumlov', 'south Bohemia', 58796, 22, 16, 7, 1, 5, 51.9, 9045, 3.13, 3.6, 124, 1845, 1879),
 (16, 'Jindrichuv Hradec', 'south Bohemia', 93931, 74, 21, 10, 1, 8, 56.9, 8427, 1.12, 1.54, 107, 1874, 1913),
 (17, 'Pelhrimov', 'south Bohemia', 74062, 99, 15, 4, 2, 7, 61.4, 8114, 2.38, 2.62, 119, 1003, 1181),
 (18, 'Pisek', 'south Bohemia', 70699, 60, 13, 2, 1, 4, 65.3, 8968, 2.83, 3.35, 131, 1740, 1910),
 (19, 'Prachatice', 'south Bohemia', 51428, 50, 11, 3, 1, 4, 52.7, 8402, 3.13, 3.98, 120, 999, 1099),
 (20, 'Strakonice', 'south Bohemia', 70646, 94, 14, 3, 1, 4, 58.4, 8547, 2.65, 3.64, 120, 1563, 1542),
 (21, 'Tabor', 'south Bohemia', 103347, 87, 16, 7, 1, 7, 67.0, 9104, 1.51, 2.07, 123, 2299, 2354),
 (22, 'Domazlice', 'west Bohemia', 58400, 65, 16, 4, 1, 6, 52.4, 8620, 1.1, 1.25, 100, 1089, 1117),
 (23, 'Cheb', 'west Bohemia', 87419, 21, 11, 4, 3, 9, 85.5, 8624, 1.79, 2.66, 102, 2879, 3198),
 (24, 'Karlovy Vary', 'west Bohemia', 122603, 25, 21, 6, 2, 8, 80.0, 8991, 1.39, 2.01, 128, 5198, 5273),
 (25, 'Klatovy', 'west Bohemia', 88757, 60, 33, 3, 2, 10, 61.7, 8554, 2.47, 2.68, 113, 1822, 2218),
 (26, 'Plzen - mesto', 'west Bohemia', 170449, 0, 0, 0, 1, 1, 100.0, 10787, 2.64, 3.09, 131, 6041, 6261),
 (27, 'Plzen - jih', 'west Bohemia', 67298, 71, 19, 10, 0, 7, 43.8, 8561, 0.65, 1.29, 110, 1029, 1127),
 (28, 'Plzen - sever', 'west Bohemia', 72541, 66, 26, 10, 0, 8, 36.9, 8594, 1.62, 2.01, 112, 1580, 1525),
 (29, 'Rokycany', 'west Bohemia', 45714, 52, 10, 5, 1, 6, 55.6, 8843, 2.82, 3.6, 113, 818, 888),
 (30, 'Sokolov', 'west Bohemia', 94812, 15, 13, 8, 2, 10, 81.8, 9650, 3.38, 3.67, 100, 2985, 2804),
 (31, 'Tachov', 'west Bohemia', 51313, 34, 12, 3, 1, 4, 59.2, 8930, 3.52, 4.2, 108, 1328, 1452),
 (32, 'Ceska Lipa', 'north Bohemia', 105058, 32, 19, 7, 2, 10, 81.0, 9272, 2.8, 3.22, 118, 4340, 4505),
 (33, 'Decin', 'north Bohemia', 133777, 24, 17, 7, 3, 11, 84.7, 8705, 5.75, 7.61, 116, 4650, 4859),
 (34, 'Chomutov', 'north Bohemia', 125236, 28, 11, 1, 4, 5, 87.7, 9675, 6.43, 7.68, 100, 5323, 5190),
 (35, 'Jablonec n. Nisou', 'north Bohemia', 88768, 10, 18, 5, 1, 7, 80.5, 8867, 1.02, 1.21, 130, 3384, 3620),
 (36, 'Liberec', 'north Bohemia', 159617, 29, 19, 8, 1, 9, 85.2, 9198, 3.33, 4.28, 131, 5796, 6132),
 (37, 'Litomerice', 'north Bohemia', 114006, 71, 26, 6, 2, 9, 62.3, 9065, 4.46, 5.39, 123, 4147, 4166),
 (38, 'Louny', 'north Bohemia', 85852, 41, 23, 4, 2, 4, 59.8, 8965, 7.08, 8.23, 104, 2653, 2822),
 (39, 'Most', 'north Bohemia', 119895, 17, 4, 3, 2, 4, 89.9, 10446, 7.34, 9.4, 90, 4947, 4743),
 (40, 'Teplice', 'north Bohemia', 128118, 9, 16, 6, 3, 8, 85.3, 9317, 6.49, 7.07, 97, 6949, 6872),
 (41, 'Usti nad Labem', 'north Bohemia', 118650, 8, 8, 5, 1, 3, 85.6, 9832, 3.32, 4.48, 114, 6445, 5471),
 (42, 'Havlickuv Brod', 'east Bohemia', 95907, 87, 25, 5, 2, 7, 59.1, 8388, 2.41, 2.94, 87, 1658, 1668),
 (43, 'Hradec Kralove', 'east Bohemia', 161854, 73, 21, 6, 1, 6, 76.3, 9425, 1.72, 2.5, 125, 4085, 3891),
 (44, 'Chrudim', 'east Bohemia', 105606, 77, 26, 7, 2, 7, 53.0, 8254, 2.79, 3.76, 97, 2166, 2325),
 (45, 'Jicin', 'east Bohemia', 77917, 85, 19, 6, 1, 5, 53.5, 8390, 2.28, 2.89, 132, 2080, 2122),
 (46, 'Nachod', 'east Bohemia', 112709, 48, 20, 7, 3, 10, 73.5, 8369, 1.79, 2.31, 117, 2854, 2618),
 (47, 'Pardubice', 'east Bohemia', 162580, 83, 26, 5, 1, 6, 72.8, 9538, 1.51, 1.81, 111, 6079, 5410),
 (48, 'Rychnov nad Kneznou', 'east Bohemia', 78955, 50, 24, 8, 1, 9, 59.0, 9060, 1.78, 2.44, 124, 1655, 1717),
 (49, 'Semily', 'east Bohemia', 75685, 31, 28, 5, 1, 9, 60.8, 8208, 1.89, 2.26, 155, 1660, 2123),
 (50, 'Svitavy', 'east Bohemia', 102609, 75, 33, 2, 3, 6, 52.0, 8187, 4.83, 5.45, 94, 2123, 2134),
 (51, 'Trutnov', 'east Bohemia', 121947, 37, 28, 7, 3, 11, 70.5, 8541, 2.51, 2.97, 131, 3496, 3839),
 (52, 'Usti nad Orlici', 'east Bohemia', 139012, 59, 41, 8, 3, 10, 61.9, 8363, 2.52, 3.49, 108, 2564, 2799),
 (53, 'Blansko', 'south Moravia', 107911, 88, 33, 6, 2, 7, 50.9, 8240, 2.53, 3.56, 99, 1850, 1903),
 (54, 'Brno - mesto', 'south Moravia', 387570, 0, 0, 0, 1, 1, 100.0, 9897, 1.6, 1.96, 140, 18721, 18696),
 (55, 'Brno - venkov', 'south Moravia', 157042, 49, 70, 18, 0, 9, 33.9, 8743, 1.88, 2.43, 111, 3659, 3894),
 (56, 'Breclav', 'south Moravia', 124605, 11, 42, 14, 1, 8, 46.0, 8772, 4.69, 4.98, 126, 2854, 3158),
 (57, 'Hodonin', 'south Moravia', 161954, 21, 37, 20, 3, 8, 48.0, 8720, 3.73, 4.5, 116, 3729, 3651),
 (58, 'Jihlava', 'south Moravia', 109164, 98, 16, 6, 1, 4, 63.6, 8757, 3.38, 3.95, 96, 2212, 2471),
 (59, 'Kromeriz', 'south Moravia', 108871, 41, 29, 7, 2, 6, 62.1, 8444, 3.24, 3.47, 106, 2595, 2305),
 (60, 'Prostejov', 'south Moravia', 110643, 49, 41, 4, 1, 4, 51.9, 8441, 3.45, 4.48, 115, 1879, 2252),
 (61, 'Trebic', 'south Moravia', 117897, 139, 28, 5, 1, 6, 53.8, 8814, 4.76, 5.74, 107, 2112, 2059),
 (62, 'Uherske Hradiste', 'south Moravia', 145688, 22, 41, 13, 2, 5, 40.7, 8544, 1.29, 1.86, 109, 2719, 2906),
 (63, 'Vyskov', 'south Moravia', 86513, 38, 36, 5, 1, 5, 50.5, 8288, 3.79, 4.52, 110, 1562, 1460),
 (64, 'Zlin', 'south Moravia', 197099, 29, 41, 10, 2, 10, 74.7, 9624, 1.6, 2.31, 145, 4484, 4265),
 (65, 'Znojmo', 'south Moravia', 114200, 101, 41, 4, 1, 4, 43.7, 8403, 5.74, 5.72, 105, 2157, 2718),
 (66, 'Zdar nad Sazavou', 'south Moravia', 125832, 151, 41, 2, 3, 5, 48.3, 8512, 3.51, 4.12, 102, 2247, 2103),
 (67, 'Bruntal', 'north Moravia', 106054, 38, 25, 6, 2, 6, 63.1, 8110, 5.77, 6.55, 109, 3244, 3079),
 (68, 'Frydek - Mistek', 'north Moravia', 228848, 15, 40, 18, 2, 6, 57.2, 9893, 4.09, 4.72, 96, 5623, 5887),
 (69, 'Jesenik', 'north Moravia', 42821, 4, 13, 5, 1, 3, 48.4, 8173, '?', 7.01, 124, '?', 1358),
 (70, 'Karvina', 'north Moravia', 285387, 0, 2, 8, 5, 7, 89.9, 10177, 6.63, 7.75, 81, 9878, 10108),
 (71, 'Novy Jicin', 'north Moravia', 161227, 5, 35, 11, 4, 10, 69.7, 8678, 5.93, 5.57, 102, 4980, 4595),
 (72, 'Olomouc', 'north Moravia', 226122, 32, 50, 7, 4, 4, 62.6, 8994, 3.8, 4.79, 110, 9672, 9208),
 (73, 'Opava', 'north Moravia', 182027, 17, 49, 12, 2, 7, 56.4, 8746, 3.33, 3.74, 90, 4355, 4433),
 (74, 'Ostrava - mesto', 'north Moravia', 323870, 0, 0, 0, 1, 1, 100.0, 10673, 4.75, 5.44, 100, 18782, 18347),
 (75, 'Prerov', 'north Moravia', 138032, 67, 30, 4, 2, 5, 64.6, 8819, 5.38, 5.66, 99, 4063, 4505),
 (76, 'Sumperk', 'north Moravia', 127369, 31, 32, 13, 2, 7, 51.2, 8369, 4.73, 5.88, 107, 3736, 2807),
 (77, 'Vsetin', 'north Moravia', 148545, 8, 35, 12, 3, 4, 53.5, 8909, 4.01, 5.56, 113, 3460, 3590)]

In [ ]:
%%sql
SELECT A3, count(A2) no_districts, sum(A9) no_cities, sum(A4) total_hab
FROM DISTRICT
WHERE NOT A3 = "Prague"
GROUP BY A3

 * sqlite:///data_berka.db
Done.

[('central Bohemia', 12, 66, 1105234),
 ('east Bohemia', 11, 86, 1234781),
 ('north Bohemia', 10, 70, 1178977),
 ('north Moravia', 11, 60, 1970302),
 ('south Bohemia', 8, 48, 700595),
 ('south Moravia', 14, 82, 2054989),
 ('west Bohemia', 10, 69, 859306)]

9. Contar ordenes permanentes (domiciliaciones) por banco y tipo de transacción

In [ ]:
%%sql
SELECT bank_to, k_symbol, count(*) as c
FROM PERMANENT_ORDER
WHERE amount < 500
GROUP BY bank_to, k_symbol
ORDER BY bank_to

 * sqlite:///data_berka.db
Done.

[('AB', ' ', 20),
 ('AB', 'POJISTNE', 16),
 ('AB', 'SIPO', 17),
 ('CD', ' ', 34),
 ('CD', 'POJISTNE', 11),
 ('CD', 'SIPO', 18),
 ('EF', ' ', 23),
 ('EF', 'POJISTNE', 21),
 ('EF', 'SIPO', 10),
 ('EF', 'UVER', 1),
 ('GH', ' ', 31),
 ('GH', 'LEASING', 1),
 ('GH', 'POJISTNE', 17),
 ('GH', 'SIPO', 16),
 ('GH', 'UVER', 4),
 ('IJ', ' ', 35),
 ('IJ', 'POJISTNE', 19),
 ('IJ', 'SIPO', 15),
 ('KL', ' ', 31),
 ('KL', 'LEASING', 1),
 ('KL', 'POJISTNE', 15),
 ('KL', 'SIPO', 15),
 ('KL', 'UVER', 2),
 ('MN', ' ', 24),
 ('MN', 'LEASING', 1),
 ('MN', 'POJISTNE', 20),
 ('MN', 'SIPO', 9),
 ('MN', 'UVER', 1),
 ('OP', ' ', 28),
 ('OP', 'POJISTNE', 23),
 ('OP', 'SIPO', 11),
 ('QR', ' ', 19),
 ('QR', 'POJISTNE', 18),
 ('QR', 'SIPO', 20),
 ('QR', 'UVER', 1),
 ('ST', ' ', 32),
 ('ST', 'POJISTNE', 17),
 ('ST', 'SIPO', 16),
 ('ST', 'UVER', 2),
 ('UV', ' ', 30),
 ('UV', 'POJISTNE', 15),
 ('UV', 'SIPO', 11),
 ('UV', 'UVER', 1),
 ('WX', ' ', 24),
 ('WX', 'POJISTNE', 25),
 ('WX', 'SIPO', 15),
 ('YZ', ' ', 28),
 ('YZ', 'LEASING', 2),
 ('YZ', 'POJISTNE', 20),
 ('YZ', 'SIPO', 14),
 ('YZ', 'UVER', 1)]

# JOIN

10. ¿Cuántas cuentas de frecuencia mensual tienen un un préstamo activo?

In [ ]:
%%sql
SELECT count(*) as Cuenta
FROM  LOAN l, ACCOUNT a
WHERE l.account_id = a.account_id
and frequency = "monthly"
and status in("C","D")

 * sqlite:///data_berka.db
Done.

[(369,)]

Incluri (AND) varias variables

In [ ]:
%%sql
SELECT loan_id, A4, A9, A10, A11,SUBSTR(c.birth_number,0,3) birthyear, l.date loan_date, amount, duration, payments, frequency, a.date acc_date, status 
FROM LOAN l, ACCOUNT a, DISTRICT d, DISPOSITION dp, CLIENT c
WHERE l.account_id = a.account_id
AND a.district_id = d.A1
AND dp.account_id = a.account_id -- join disposition y account
AND dp.client_id = c.client_id  -- join disposition y client
AND dp.type = "OWNER"
AND status in ("A", "B")
ORDER BY amount DESC, a.date DESC
LIMIT 10

 * sqlite:///data_berka.db
Done.

[(6228, 77963, 4, 51.5, 8546, '40', 931201, 464520, 60, 7742, 'weekly', 930319, 'B'),
 (6038, 1204953, 1, 100.0, 12541, '40', 940810, 323472, 48, 6739, 'monthly', 930621, 'A'),
 (5918, 67298, 7, 43.8, 8561, '64', 940604, 300204, 36, 8339, 'monthly', 930605, 'A'),
 (5395, 106054, 6, 63.1, 8110, '66', 940730, 299088, 36, 8308, 'monthly', 930606, 'B'),
 (6526, 86513, 5, 50.5, 8288, '58', 950103, 288468, 36, 8013, 'monthly', 940829, 'A'),
 (6232, 124605, 8, 46.0, 8772, '49', 940708, 276660, 36, 7685, 'monthly', 930828, 'B'),
 (7240, 1204953, 1, 100.0, 12541, '78', 930906, 274740, 60, 4579, 'weekly', 930214, 'A'),
 (6244, 1204953, 1, 100.0, 12541, '37', 950108, 270648, 36, 7518, 'weekly', 940307, 'B'),
 (6725, 51428, 4, 52.7, 8402, '48', 950623, 265320, 36, 7370, 'monthly', 930918, 'A'),
 (7176, 75637, 7, 36.5, 9622, '76', 951028, 260028, 36, 7223, 'monthly', 931208, 'A')]

11. Domiciliaciones en cuentas de actualización semanal de alquiler en cuentas de Praga

In [ ]:
%%sql
SELECT order_id, p.account_id, amount
FROM PERMANENT_ORDER p, ACCOUNT a, DISTRICT d
WHERE p.account_id = a.account_id
and a.district_id = d.A1
and k_symbol = "LEASING"
and frequency = "weekly"
and A3 = "Prague"

 * sqlite:///data_berka.db
Done.

[(29514, 72, 2923),
 (30250, 573, 2249),
 (30944, 1056, 2531.7),
 (34056, 3141, 1087),
 (35237, 3959, 1680.6),
 (40429, 7465, 1060.6)]


12. Domiciliaciones (*órdenes*) semanales para alquiler (*leasing*) en cuentas de Praga

 - Ordenes permanentes de alquiler (*leasing*) y semanales (*weekly*)
 - Relación con cuentas que tienen región Praga

In [ ]:
%%sql
SELECT order_id, k_symbol, bank_to, a.account_id, a.frequency, d.A2, d.A3
FROM PERMANENT_ORDER p, ACCOUNT a, DISTRICT d
WHERE p.account_id = a.account_id and a.district_id = d.A1
    and k_symbol = "LEASING" and a.frequency = "weekly" and d.A3 = "Prague"

 * sqlite:///data_berka.db
Done.

[(29514, 'LEASING', 'OP', 72, 'weekly', 'Hl.m. Praha', 'Prague'),
 (30250, 'LEASING', 'CD', 573, 'weekly', 'Hl.m. Praha', 'Prague'),
 (30944, 'LEASING', 'IJ', 1056, 'weekly', 'Hl.m. Praha', 'Prague'),
 (34056, 'LEASING', 'OP', 3141, 'weekly', 'Hl.m. Praha', 'Prague'),
 (35237, 'LEASING', 'AB', 3959, 'weekly', 'Hl.m. Praha', 'Prague'),
 (40429, 'LEASING', 'ST', 7465, 'weekly', 'Hl.m. Praha', 'Prague')]

13. Transacciones relacionadas con pensiones (DUCHOD) en Plzen desde el banco MN

(limitar a 10)

In [ ]:

%%sql
SELECT trans_id, a.account_id, a.frequency, t.type, k_symbol, bank
FROM TRANS t, ACCOUNT a, DISTRICT d
WHERE t.account_id = a.account_id and a.district_id = d.A1
  and k_symbol = "DUCHOD" and bank = "MN" and d.A2 like "Plzen%"  
LIMIT 10

 * sqlite:///data_berka.db
Done.

[(47969, 161, 'monthly', 'PRIJEM', 'DUCHOD', 'MN'),
 (47970, 161, 'monthly', 'PRIJEM', 'DUCHOD', 'MN'),
 (47971, 161, 'monthly', 'PRIJEM', 'DUCHOD', 'MN'),
 (47972, 161, 'monthly', 'PRIJEM', 'DUCHOD', 'MN'),
 (47973, 161, 'monthly', 'PRIJEM', 'DUCHOD', 'MN'),
 (47974, 161, 'monthly', 'PRIJEM', 'DUCHOD', 'MN'),
 (47975, 161, 'monthly', 'PRIJEM', 'DUCHOD', 'MN'),
 (47976, 161, 'monthly', 'PRIJEM', 'DUCHOD', 'MN'),
 (47977, 161, 'monthly', 'PRIJEM', 'DUCHOD', 'MN'),
 (1098524, 3753, 'monthly', 'PRIJEM', 'DUCHOD', 'MN')]

# Subconsultas

14. Prestamos cuya cantidad es superior a la media de los clientes de Praga

- Cantidad media prestada a los cuentas de Praga 



```
SELECT avg(l.amount)
FROM LOAN l, ACCOUNT a, DISTRICT D
WHERE l.account_id = a.account_id and a.district_id = d.A1 
and d.A3 = "Prague"

```

In [ ]:
%%sql
SELECT avg(l.amount)
FROM LOAN l, ACCOUNT a, DISTRICT d
WHERE l.account_id = a.account_id
AND a.district_id = d.A1
and d.A3 = "Prague"

 * sqlite:///data_berka.db
Done.

[(153957.2857142857,)]

- Consultar los préstamos superiores a esa cantidad

In [ ]:
%%sql
SELECT count(*) 
FROM LOAN
WHERE amount > (SELECT avg(l.amount)
      FROM LOAN l, ACCOUNT a, DISTRICT d
      WHERE l.account_id = a.account_id
      AND a.district_id = d.A1
      and d.A3 = "Prague")

 * sqlite:///data_berka.db
Done.

[(277,)]

Lo anterior fue la cantidad con (count). Ahora con toda la información de los préstamos

In [ ]:
%%sql
SELECT * FROM LOAN 
WHERE amount > (SELECT avg(l.amount)
        FROM LOAN l, ACCOUNT a, DISTRICT d
        WHERE l.account_id = a.account_id and a.district_id = d.A1  
        and d.A3 = "Prague")
ORDER BY amount DESC

 * sqlite:///data_berka.db
Done.

[(6534, 7542, 971019, 590820, 60, 9847, 'C'),
 (6791, 8926, 980123, 566640, 60, 9444, 'C'),
 (5447, 2335, 971112, 541200, 60, 9020, 'D'),
 (5132, 817, 950217, 538500, 60, 8975, 'C'),
 (5569, 2936, 980120, 504000, 60, 8400, 'C'),
 (6436, 7049, 980522, 495180, 60, 8253, 'C'),
 (7142, 10451, 941219, 482940, 60, 8049, 'D'),
 (6415, 6950, 970212, 475680, 48, 9910, 'C'),
 (6625, 7966, 970907, 473280, 60, 7888, 'D'),
 (5043, 339, 971225, 468060, 60, 7801, 'C'),
 (5486, 2516, 970613, 466608, 48, 9721, 'C'),
 (5976, 4794, 971227, 465504, 48, 9698, 'D'),
 (5970, 4774, 950709, 465072, 48, 9689, 'C'),
 (6228, 6034, 931201, 464520, 60, 7742, 'B'),
 (5731, 3711, 971105, 460980, 60, 7683, 'D'),
 (5725, 3679, 960723, 444864, 48, 9268, 'C'),
 (5561, 2910, 980829, 437460, 60, 7291, 'C'),
 (5491, 2545, 980213, 428784, 48, 8933, 'C'),
 (7101, 10297, 961118, 421008, 48, 8771, 'C'),
 (7304, 11349, 951029, 419880, 60, 6998, 'C'),
 (7154, 10520, 961205, 417600, 60, 6960, 'C'),
 (6704, 8377, 950601, 417060, 60, 6951, 'C'),
 (5419, 2246, 970205, 415800, 60, 6930, 'C'),
 (6237, 6075, 980106, 407952, 48, 8499, 'D'),
 (5830, 4190, 970828, 405780, 60, 6763, 'C'),
 (5938, 4650, 960825, 402000, 60, 6700, 'C'),
 (6055, 5181, 970428, 399120, 60, 6652, 'C'),
 (6272, 6226, 941220, 398640, 60, 6644, 'C'),
 (5329, 1862, 961016, 396120, 60, 6602, 'C'),
 (7271, 11186, 961002, 392460, 60, 6541, 'C'),
 (6338, 6592, 970824, 390660, 60, 6511, 'C'),
 (6554, 7637, 970129, 390096, 48, 8127, 'C'),
 (5589, 3005, 980605, 390000, 48, 8125, 'C'),
 (5236, 1374, 970915, 389136, 48, 8107, 'C'),
 (5282, 1583, 960824, 388512, 48, 8094, 'D'),
 (5318, 1808, 980930, 385584, 48, 8033, 'C'),
 (7209, 10857, 971130, 385560, 60, 6426, 'D'),
 (5174, 1093, 970613, 385104, 48, 8023, 'C'),
 (5563, 2912, 960229, 380160, 60, 6336, 'C'),
 (6926, 9455, 980207, 374760, 60, 6246, 'C'),
 (6585, 7795, 961029, 372120, 60, 6202, 'C'),
 (5041, 319, 970711, 369000, 60, 6150, 'C'),
 (6109, 5422, 960603, 368880, 60, 6148, 'C'),
 (6239, 6083, 970928, 360864, 48, 7518, 'D'),
 (5494, 2572, 960613, 360000, 48, 7500, 'C'),
 (6006, 4948, 961115, 359760, 60, 5996, 'C'),
 (5063, 442, 970710, 357840, 48, 7455, 'D'),
 (4989, 105, 981205, 352704, 48, 7348, 'C'),
 (6118, 5477, 971004, 349392, 48, 7279, 'C'),
 (7100, 10280, 971231, 348120, 60, 5802, 'C'),
 (5418, 2245, 950116, 347952, 48, 7249, 'C'),
 (6938, 9504, 970310, 341280, 60, 5688, 'C'),
 (7195, 10774, 980423, 339168, 48, 7066, 'C'),
 (5532, 2754, 970504, 335280, 48, 6985, 'C'),
 (5991, 4858, 980727, 335184, 48, 6983, 'D'),
 (5772, 3906, 980308, 334620, 60, 5577, 'C'),
 (6705, 8381, 970725, 333648, 48, 6951, 'D'),
 (5042, 330, 980712, 331584, 48, 6908, 'C'),
 (7004, 9869, 950315, 331560, 60, 5526, 'C'),
 (5865, 4354, 981030, 327660, 60, 5461, 'C'),
 (6038, 5120, 940810, 323472, 48, 6739, 'A'),
 (6821, 9037, 980915, 321936, 48, 6707, 'C'),
 (6235, 6062, 980419, 321360, 60, 5356, 'C'),
 (5889, 4456, 980209, 321240, 60, 5354, 'C'),
 (5611, 3115, 961115, 321180, 60, 5353, 'C'),
 (6063, 5213, 960425, 320976, 48, 6687, 'D'),
 (6550, 7614, 960518, 320592, 48, 6679, 'C'),
 (4967, 37, 981014, 318480, 60, 5308, 'D'),
 (6028, 5072, 970209, 317520, 60, 5292, 'C'),
 (7292, 11317, 981122, 317460, 60, 5291, 'C'),
 (5724, 3678, 950205, 316140, 60, 5269, 'D'),
 (5435, 2279, 980601, 314688, 48, 6556, 'C'),
 (7227, 10942, 951002, 314520, 60, 5242, 'C'),
 (7050, 10065, 970923, 311232, 48, 6484, 'C'),
 (6695, 8320, 970604, 309660, 60, 5161, 'C'),
 (6540, 7562, 951231, 309600, 48, 6450, 'C'),
 (5145, 915, 950916, 309552, 48, 6449, 'C'),
 (5758, 3859, 970502, 307200, 60, 5120, 'D'),
 (7085, 10202, 970619, 305424, 48, 6363, 'C'),
 (6087, 5313, 940227, 300660, 60, 5011, 'C'),
 (7001, 9859, 970810, 300600, 60, 5010, 'C'),
 (5918, 4576, 940604, 300204, 36, 8339, 'A'),
 (5395, 2176, 940730, 299088, 36, 8308, 'B'),
 (6350, 6678, 970709, 294384, 48, 6133, 'C'),
 (5363, 2051, 970422, 293880, 60, 4898, 'D'),
 (5469, 2445, 971226, 293160, 60, 4886, 'C'),
 (5354, 2000, 980714, 290820, 60, 4847, 'C'),
 (6175, 5735, 960221, 290700, 60, 4845, 'D'),
 (6007, 4949, 970830, 289920, 48, 6040, 'C'),
 (6435, 7045, 970616, 288720, 48, 6015, 'C'),
 (6526, 7523, 950103, 288468, 36, 8013, 'A'),
 (6736, 8558, 940614, 288360, 60, 4806, 'C'),
 (6153, 5632, 950725, 285600, 60, 4760, 'C'),
 (6877, 9241, 970619, 285240, 60, 4754, 'C'),
 (5148, 940, 960529, 284280, 60, 4738, 'C'),
 (7295, 11328, 980718, 280440, 60, 4674, 'C'),
 (6962, 9646, 980402, 279072, 48, 5814, 'C'),
 (5593, 3037, 960418, 277884, 36, 7719, 'D'),
 (6232, 6051, 940708, 276660, 36, 7685, 'B'),
 (6073, 5263, 961112, 276300, 60, 4605, 'C'),
 (5644, 3293, 981127, 276084, 36, 7669, 'C'),
 (7240, 11013, 930906, 274740, 60, 4579, 'A'),
 (5568, 2933, 940517, 272520, 60, 4542, 'C'),
 (6851, 9138, 970603, 272220, 60, 4537, 'D'),
 (6859, 9167, 980307, 272220, 60, 4537, 'C'),
 (5719, 3664, 970920, 271584, 48, 5658, 'C'),
 (5365, 2055, 980719, 271260, 60, 4521, 'C'),
 (6244, 6118, 950108, 270648, 36, 7518, 'B'),
 (6296, 6358, 960806, 270384, 48, 5633, 'C'),
 (7167, 10644, 980618, 269964, 36, 7499, 'C'),
 (5556, 2872, 970519, 268320, 60, 4472, 'C'),
 (7147, 10478, 980102, 267600, 48, 5575, 'C'),
 (6712, 8405, 951014, 266220, 60, 4437, 'C'),
 (6725, 8489, 950623, 265320, 36, 7370, 'A'),
 (4988, 103, 971206, 265320, 36, 7370, 'D'),
 (5082, 501, 961024, 262980, 60, 4383, 'C'),
 (7122, 10365, 970104, 260640, 36, 7240, 'D'),
 (6655, 8085, 971017, 260400, 60, 4340, 'D'),
 (7176, 10663, 951028, 260028, 36, 7223, 'A'),
 (7104, 10320, 931213, 259740, 60, 4329, 'A'),
 (6012, 4994, 960803, 258444, 36, 7179, 'C'),
 (5614, 3137, 980921, 253560, 60, 4226, 'C'),
 (5606, 3084, 960828, 253512, 36, 7042, 'D'),
 (5170, 1071, 940120, 253200, 60, 4220, 'C'),
 (5169, 1068, 980924, 253200, 60, 4220, 'C'),
 (5060, 426, 940719, 252060, 60, 4201, 'D'),
 (7164, 10613, 980815, 249792, 48, 5204, 'C'),
 (5350, 1967, 960421, 249312, 48, 5194, 'C'),
 (5310, 1762, 950428, 248148, 36, 6893, 'A'),
 (6255, 6158, 970208, 247920, 48, 5165, 'D'),
 (6254, 6157, 971228, 247920, 48, 5165, 'C'),
 (6698, 8327, 960310, 247728, 48, 5161, 'C'),
 (5837, 4260, 940629, 244560, 60, 4076, 'C'),
 (6955, 9627, 951122, 244368, 48, 5091, 'C'),
 (6748, 8645, 981208, 240900, 60, 4015, 'C'),
 (6083, 5305, 980331, 240528, 48, 5011, 'C'),
 (5319, 1811, 940623, 239460, 60, 3991, 'C'),
 (7088, 10233, 970503, 239160, 60, 3986, 'C'),
 (6675, 8158, 971101, 238716, 36, 6631, 'C'),
 (6450, 7099, 980610, 234336, 48, 4882, 'C'),
 (7049, 10063, 970624, 233424, 36, 6484, 'C'),
 (6178, 5742, 951216, 232560, 48, 4845, 'C'),
 (6173, 5724, 970108, 232560, 48, 4845, 'C'),
 (7057, 10093, 951020, 231696, 36, 6436, 'A'),
 (5520, 2699, 980830, 231168, 48, 4816, 'C'),
 (5051, 378, 971011, 230400, 60, 3840, 'C'),
 (6738, 8566, 940929, 230220, 36, 6395, 'B'),
 (5428, 2262, 981202, 230220, 36, 6395, 'C'),
 (6940, 9510, 961122, 228276, 36, 6341, 'C'),
 (6808, 8982, 941012, 227880, 36, 6330, 'A'),
 (6932, 9491, 980625, 225504, 48, 4698, 'C'),
 (6151, 5628, 950425, 225420, 60, 3757, 'C'),
 (6686, 8260, 940825, 224604, 36, 6239, 'A'),
 (5625, 3189, 961215, 222180, 60, 3703, 'D'),
 (6142, 5591, 970121, 221880, 60, 3698, 'C'),
 (5876, 4413, 950208, 221280, 48, 4610, 'C'),
 (6715, 8411, 960506, 220620, 60, 3677, 'C'),
 (6568, 7713, 980225, 220440, 60, 3674, 'C'),
 (6660, 8094, 970509, 220428, 36, 6123, 'C'),
 (5973, 4784, 971124, 219456, 48, 4572, 'C'),
 (7037, 10022, 980103, 218064, 48, 4543, 'C'),
 (7243, 11042, 951204, 217152, 36, 6032, 'A'),
 (5128, 808, 960411, 215616, 48, 4492, 'D'),
 (7066, 10131, 940502, 215388, 36, 5983, 'B'),
 (6861, 9179, 980228, 215040, 60, 3584, 'C'),
 (5369, 2080, 970912, 214596, 36, 5961, 'C'),
 (5989, 4852, 960304, 213300, 36, 5925, 'C'),
 (7255, 11096, 970609, 213300, 60, 3555, 'C'),
 (5823, 4144, 980621, 212976, 36, 5916, 'C'),
 (6336, 6555, 940331, 212400, 36, 5900, 'A'),
 (7035, 10005, 980729, 210744, 36, 5854, 'C'),
 (5086, 525, 970716, 210384, 48, 4383, 'C'),
 (6120, 5481, 940911, 209184, 48, 4358, 'A'),
 (5334, 1876, 980910, 209040, 24, 8710, 'C'),
 (7168, 10645, 980705, 208332, 36, 5787, 'C'),
 (6647, 8051, 940601, 208320, 48, 4340, 'A'),
 (5126, 790, 940724, 208128, 48, 4336, 'B'),
 (5674, 3418, 970610, 207264, 48, 4318, 'C'),
 (5351, 1978, 941204, 205200, 36, 5700, 'A'),
 (5963, 4746, 970907, 204780, 60, 3413, 'C'),
 (5160, 1011, 951218, 204000, 60, 3400, 'C'),
 (6468, 7176, 971130, 203940, 60, 3399, 'C'),
 (6097, 5362, 970821, 202848, 48, 4226, 'C'),
 (5312, 1772, 960313, 202788, 36, 5633, 'C'),
 (5470, 2456, 960415, 200976, 48, 4187, 'C'),
 (5450, 2345, 941211, 199680, 60, 3328, 'C'),
 (7166, 10630, 950624, 198240, 24, 8260, 'A'),
 (7181, 10679, 971002, 197808, 24, 8242, 'C'),
 (7226, 10940, 940223, 197748, 36, 5493, 'A'),
 (5072, 472, 970428, 196800, 24, 8200, 'D'),
 (7171, 10650, 980224, 196224, 48, 4088, 'C'),
 (6580, 7769, 940522, 196080, 48, 4085, 'A'),
 (7036, 10019, 960925, 194940, 36, 5415, 'C'),
 (6403, 6924, 951205, 194880, 48, 4060, 'C'),
 (7129, 10404, 980301, 194280, 60, 3238, 'C'),
 (5281, 1580, 971127, 194256, 24, 8094, 'C'),
 (6442, 7082, 980208, 194160, 48, 4045, 'C'),
 (6072, 5256, 940510, 193968, 36, 5388, 'A'),
 (5887, 4448, 941003, 192744, 36, 5354, 'A'),
 (5886, 4447, 961031, 192744, 36, 5354, 'C'),
 (5176, 1106, 941112, 192552, 24, 8023, 'B'),
 (6545, 7606, 951212, 191880, 60, 3198, 'C'),
 (6872, 9227, 980429, 191580, 60, 3193, 'C'),
 (5270, 1528, 970721, 191088, 48, 3981, 'C'),
 (5293, 1656, 981029, 189792, 48, 3954, 'C'),
 (6594, 7824, 940928, 189696, 24, 7904, 'B'),
 (6589, 7815, 960101, 189696, 24, 7904, 'A'),
 (6836, 9093, 940803, 189300, 60, 3155, 'C'),
 (5151, 960, 950524, 189060, 60, 3151, 'C'),
 (6933, 9493, 950909, 188688, 48, 3931, 'C'),
 (6908, 9353, 970608, 188616, 24, 7859, 'C'),
 (5158, 1004, 980411, 188532, 36, 5237, 'C'),
 (5045, 347, 950501, 187224, 24, 7801, 'B'),
 (5136, 846, 960728, 187104, 24, 7796, 'A'),
 (6810, 9006, 960608, 186384, 48, 3883, 'C'),
 (6793, 8931, 970130, 186300, 60, 3105, 'C'),
 (5414, 2228, 950329, 185952, 48, 3874, 'C'),
 (6746, 8639, 980606, 185640, 60, 3094, 'C'),
 (5226, 1318, 981011, 185544, 36, 5154, 'C'),
 (6207, 5912, 980623, 184620, 60, 3077, 'C'),
 (5209, 1250, 961125, 182640, 48, 3805, 'C'),
 (7262, 11135, 940301, 182628, 36, 5073, 'A'),
 (5409, 2218, 951118, 182040, 60, 3034, 'C'),
 (6302, 6397, 960916, 181020, 60, 3017, 'C'),
 (6011, 4981, 961128, 179328, 48, 3736, 'C'),
 (5140, 873, 980224, 178500, 60, 2975, 'C'),
 (6196, 5837, 970914, 177804, 36, 4939, 'C'),
 (5624, 3166, 950103, 177744, 48, 3703, 'D'),
 (6147, 5602, 971228, 177504, 48, 3698, 'C'),
 (5360, 2035, 980125, 176328, 36, 4898, 'C'),
 (6961, 9645, 960606, 176148, 36, 4893, 'C'),
 (5699, 3562, 980524, 174960, 24, 7290, 'C'),
 (5698, 3556, 980922, 174840, 60, 2914, 'C'),
 (6111, 5428, 930924, 174744, 24, 7281, 'B'),
 (6112, 5442, 940617, 174744, 24, 7281, 'B'),
 (6732, 8533, 960919, 174048, 48, 3626, 'C'),
 (6066, 5228, 940711, 173808, 24, 7242, 'A'),
 (6734, 8547, 960530, 173016, 36, 4806, 'C'),
 (5304, 1718, 980820, 172272, 24, 7178, 'C'),
 (6841, 9104, 940807, 172080, 48, 3585, 'A'),
 (6078, 5283, 980909, 170832, 48, 3559, 'C'),
 (6755, 8713, 980724, 170700, 60, 2845, 'C'),
 (6552, 7632, 980108, 170448, 48, 3551, 'C'),
 (5390, 2167, 941030, 170256, 24, 7094, 'A'),
 (7241, 11021, 950304, 168984, 24, 7041, 'B'),
 (5956, 4725, 971104, 168264, 36, 4674, 'C'),
 (7055, 10079, 940406, 167100, 60, 2785, 'C'),
 (5316, 1801, 930711, 165960, 36, 4610, 'A'),
 (4973, 67, 960502, 165960, 24, 6915, 'A'),
 (5265, 1498, 981007, 165780, 60, 2763, 'C'),
 (6014, 4999, 970518, 165168, 36, 4588, 'C'),
 (5482, 2496, 960112, 165120, 60, 2752, 'C'),
 (6871, 9225, 970413, 164256, 48, 3422, 'C'),
 (5850, 4293, 970522, 164196, 36, 4561, 'C'),
 (5269, 1527, 941119, 164052, 36, 4557, 'B'),
 (6856, 9156, 981201, 163332, 36, 4537, 'C'),
 (5942, 4681, 970315, 162624, 48, 3388, 'C'),
 (4990, 110, 970908, 162576, 36, 4516, 'C'),
 (5337, 1886, 960731, 162468, 36, 4513, 'C'),
 (5706, 3608, 960524, 161496, 36, 4486, 'C'),
 (5027, 276, 981202, 160920, 36, 4470, 'C'),
 (6633, 7997, 980205, 160656, 24, 6694, 'C'),
 (5451, 2350, 970511, 159744, 48, 3328, 'C'),
 (5804, 4079, 950405, 158976, 48, 3312, 'C'),
 (5713, 3629, 950530, 158760, 60, 2646, 'C'),
 (6104, 5395, 970905, 158184, 36, 4394, 'C'),
 (6948, 9560, 980315, 157068, 36, 4363, 'C'),
 (5453, 2361, 950401, 156672, 36, 4352, 'A'),
 (5527, 2728, 980615, 156420, 60, 2607, 'C'),
 (5124, 785, 980212, 156096, 36, 4336, 'C'),
 (6667, 8127, 960715, 155880, 24, 6495, 'A'),
 (7279, 11244, 971211, 155760, 24, 6490, 'C'),
 (6471, 7184, 960804, 155640, 24, 6485, 'A'),
 (5591, 3021, 961204, 155616, 48, 3242, 'C'),
 (6818, 9030, 961212, 155616, 48, 3242, 'C'),
 (7189, 10728, 960321, 154656, 48, 3222, 'C'),
 (7235, 10973, 931013, 154416, 48, 3217, 'A')]

# Repaso de Join/Group By

Group by-> ordenar

## Objetivo 2.1

15 . Clientes de Praga con préstamos según su estado

- ¿Cuántos clientes hay en Praga?
- ¿Cuántas cuentas tienen asociados clientes en Praga?
- ¿cuántas de esas cuentas tienen asociados un préstamo?
- Necesito saber cuántos hay por cada estado (*status*)

In [ ]:
%%sql 
SELECT status, count(*)
FROM CLIENT c, DISTRICT d, DISPOSITION dp, LOAN l 
WHERE c.district_id = d.A1 and c.client_id = dp.client_id
and l.account_id = dp.account_id and d.A3 = "Prague"
GROUP BY status

 * sqlite:///data_berka.db
Done.

[('A', 37), ('B', 3), ('C', 55), ('D', 3)]

## Ejercicio

> cantidad de dinero medio en transacciones de clientes propietarios de cuentas en Kolin (owned accounts)

In [ ]:
%%sql
SELECT c.client_id, avg (amount) as av
from client c, district d, disposition ds, account a, trans t
WHERE c.district_id = d.A1 and c.client_id = ds.client_id
    and ds.account_id = a.account_id and a.account_id = t.account_id
and d.A2 = "Kolin" and ds.type = "OWNER" 
GROUP BY c.client_id
ORDER BY av DESC
LIMIT 10

 * sqlite:///data_berka.db
Done.

[(5249, 15611.831578947369),
 (3378, 14803.997402597402),
 (1388, 14464.587096774194),
 (6803, 13825.125153374232),
 (8091, 13227.722338204592),
 (3298, 13074.464857881138),
 (1806, 13037.759375),
 (4331, 12644.448051948051),
 (4974, 12023.291743119267),
 (3080, 11784.50460251046)]

> sanction interest if negative balance Cesky Krumlov


> stands for loan payment in Praha from the bank EF

# Extra: Left Join

1. ¿Cuántas cuentas hay? 4500
2. ¿Cuántas cuentas hay con préstamos? (inner join) 682
3. Cuentas con los datos de los préstamos si los hay
4. los ordenamos por cantidad

con la función OUTER -> es otro comando

INNER para unir tablas

Para obtener las cuentas con préstamos los 682 -> con count

Obtener el total de cuentas -> solamente count

In [ ]:
%%sql 
SELECT count (*)
FROM ACCOUNT

 * sqlite:///data_berka.db
Done.

[(4500,)]

In [ ]:
%%sql 
SELECT a.account_id, count (*)
FROM ACCOUNT a INNER JOIN LOAN l ON a.account_id = l.account_id
ORDER BY amount DESC

 * sqlite:///data_berka.db
Done.

[(8645, 682)]

In [ ]:
%%sql 
SELECT a.account_id, a.date, l.amount, l.status, l.payments, l.duration
FROM ACCOUNT a INNER JOIN LOAN l ON a.account_id = l.account_id
ORDER BY amount DESC

 * sqlite:///data_berka.db
Done.

[(7542, 960516, 590820, 'C', 9847, 60),
 (8926, 970321, 566640, 'C', 9444, 60),
 (2335, 960404, 541200, 'D', 9020, 60),
 (817, 940318, 538500, 'C', 8975, 60),
 (2936, 960327, 504000, 'C', 8400, 60),
 (7049, 971012, 495180, 'C', 8253, 60),
 (10451, 930829, 482940, 'D', 8049, 60),
 (6950, 961012, 475680, 'C', 9910, 48),
 (7966, 961227, 473280, 'D', 7888, 60),
 (339, 960911, 468060, 'C', 7801, 60),
 (2516, 951116, 466608, 'C', 9721, 48),
 (4794, 961218, 465504, 'D', 9698, 48),
 (4774, 940114, 465072, 'C', 9689, 48),
 (6034, 930319, 464520, 'B', 7742, 60),
 (3711, 970508, 460980, 'D', 7683, 60),
 (3679, 950815, 444864, 'C', 9268, 48),
 (2910, 971021, 437460, 'C', 7291, 60),
 (2545, 961204, 428784, 'C', 8933, 48),
 (10297, 960119, 421008, 'C', 8771, 48),
 (11349, 950526, 419880, 'C', 6998, 60),
 (10520, 951024, 417600, 'C', 6960, 60),
 (8377, 931120, 417060, 'C', 6951, 60),
 (2246, 960425, 415800, 'C', 6930, 60),
 (6075, 960915, 407952, 'D', 8499, 48),
 (4190, 951004, 405780, 'C', 6763, 60),
 (4650, 951015, 402000, 'C', 6700, 60),
 (5181, 960203, 399120, 'C', 6652, 60),
 (6226, 930726, 398640, 'C', 6644, 60),
 (1862, 950415, 396120, 'C', 6602, 60),
 (11186, 941124, 392460, 'C', 6541, 60),
 (6592, 961020, 390660, 'C', 6511, 60),
 (7637, 960819, 390096, 'C', 8127, 48),
 (3005, 970111, 390000, 'C', 8125, 48),
 (1374, 960926, 389136, 'C', 8107, 48),
 (1583, 941117, 388512, 'D', 8094, 48),
 (1808, 970516, 385584, 'C', 8033, 48),
 (10857, 961002, 385560, 'D', 6426, 60),
 (1093, 960114, 385104, 'C', 8023, 48),
 (2912, 940730, 380160, 'C', 6336, 60),
 (9455, 961103, 374760, 'C', 6246, 60),
 (7795, 950105, 372120, 'C', 6202, 60),
 (319, 951017, 369000, 'C', 6150, 60),
 (5422, 941022, 368880, 'C', 6148, 60),
 (6083, 960919, 360864, 'D', 7518, 48),
 (2572, 941113, 360000, 'C', 7500, 48),
 (4948, 950729, 359760, 'C', 5996, 60),
 (442, 970330, 357840, 'D', 7455, 48),
 (105, 970710, 352704, 'C', 7348, 48),
 (5477, 951217, 349392, 'C', 7279, 48),
 (10280, 961201, 348120, 'C', 5802, 60),
 (2245, 930330, 347952, 'C', 7249, 48),
 (9504, 960129, 341280, 'C', 5688, 60),
 (10774, 970705, 339168, 'C', 7066, 48),
 (2754, 960126, 335280, 'C', 6985, 48),
 (4858, 970621, 335184, 'D', 6983, 48),
 (3906, 970708, 334620, 'C', 5577, 60),
 (8381, 960917, 333648, 'D', 6951, 48),
 (330, 961124, 331584, 'C', 6908, 48),
 (9869, 930821, 331560, 'C', 5526, 60),
 (4354, 970108, 327660, 'C', 5461, 60),
 (5120, 930621, 323472, 'A', 6739, 48),
 (9037, 961022, 321936, 'C', 6707, 48),
 (6062, 960828, 321360, 'C', 5356, 60),
 (4456, 960903, 321240, 'C', 5354, 60),
 (3115, 960327, 321180, 'C', 5353, 60),
 (5213, 950818, 320976, 'D', 6687, 48),
 (7614, 950208, 320592, 'C', 6679, 48),
 (37, 970818, 318480, 'D', 5308, 60),
 (5072, 960412, 317520, 'C', 5292, 60),
 (11317, 970711, 317460, 'C', 5291, 60),
 (3678, 930324, 316140, 'D', 5269, 60),
 (2279, 961030, 314688, 'C', 6556, 48),
 (10942, 940605, 314520, 'C', 5242, 60),
 (10065, 960330, 311232, 'C', 6484, 48),
 (8320, 970119, 309660, 'C', 5161, 60),
 (7562, 950117, 309600, 'C', 6450, 48),
 (915, 950118, 309552, 'C', 6449, 48),
 (3859, 960423, 307200, 'D', 5120, 60),
 (10202, 960708, 305424, 'C', 6363, 48),
 (5313, 930429, 300660, 'C', 5011, 60),
 (9859, 960708, 300600, 'C', 5010, 60),
 (4576, 930605, 300204, 'A', 8339, 36),
 (2176, 930606, 299088, 'B', 8308, 36),
 (6678, 960103, 294384, 'C', 6133, 48),
 (2051, 951108, 293880, 'D', 4898, 60),
 (2445, 960707, 293160, 'C', 4886, 60),
 (2000, 970806, 290820, 'C', 4847, 60),
 (5735, 950125, 290700, 'D', 4845, 60),
 (4949, 961014, 289920, 'C', 6040, 48),
 (7045, 961226, 288720, 'C', 6015, 48),
 (7523, 940829, 288468, 'A', 8013, 36),
 (8558, 940227, 288360, 'C', 4806, 60),
 (5632, 941115, 285600, 'C', 4760, 60),
 (9241, 960925, 285240, 'C', 4754, 60),
 (940, 941115, 284280, 'C', 4738, 60),
 (11328, 961105, 280440, 'C', 4674, 60),
 (9646, 960730, 279072, 'C', 5814, 48),
 (3037, 940526, 277884, 'D', 7719, 36),
 (6051, 930828, 276660, 'B', 7685, 36),
 (5263, 950714, 276300, 'C', 4605, 60),
 (3293, 970808, 276084, 'C', 7669, 36),
 (11013, 930214, 274740, 'A', 4579, 60),
 (2933, 930618, 272520, 'C', 4542, 60),
 (9138, 960718, 272220, 'D', 4537, 60),
 (9167, 970402, 272220, 'C', 4537, 60),
 (3664, 960428, 271584, 'C', 5658, 48),
 (2055, 970417, 271260, 'C', 4521, 60),
 (6118, 940307, 270648, 'B', 7518, 36),
 (6358, 950527, 270384, 'C', 5633, 48),
 (10644, 970712, 269964, 'C', 7499, 36),
 (2872, 960904, 268320, 'C', 4472, 60),
 (10478, 960224, 267600, 'C', 5575, 48),
 (8405, 940510, 266220, 'C', 4437, 60),
 (8489, 930918, 265320, 'A', 7370, 36),
 (103, 960310, 265320, 'D', 7370, 36),
 (501, 951021, 262980, 'C', 4383, 60),
 (10365, 950902, 260640, 'D', 7240, 36),
 (8085, 960408, 260400, 'D', 4340, 60),
 (10663, 931208, 260028, 'A', 7223, 36),
 (10320, 930711, 259740, 'A', 4329, 60),
 (4994, 960111, 258444, 'C', 7179, 36),
 (3137, 961215, 253560, 'C', 4226, 60),
 (3084, 960128, 253512, 'D', 7042, 36),
 (1071, 930510, 253200, 'C', 4220, 60),
 (1068, 970215, 253200, 'C', 4220, 60),
 (426, 931129, 252060, 'D', 4201, 60),
 (10613, 971104, 249792, 'C', 5204, 48),
 (1967, 950213, 249312, 'C', 5194, 48),
 (1762, 931211, 248148, 'A', 6893, 36),
 (6158, 960513, 247920, 'D', 5165, 48),
 (6157, 961111, 247920, 'C', 5165, 48),
 (8327, 950808, 247728, 'C', 5161, 48),
 (4260, 931014, 244560, 'C', 4076, 60),
 (9627, 940722, 244368, 'C', 5091, 48),
 (8645, 970623, 240900, 'C', 4015, 60),
 (5305, 960916, 240528, 'C', 5011, 48),
 (1811, 930922, 239460, 'C', 3991, 60),
 (10233, 960221, 239160, 'C', 3986, 60),
 (8158, 960616, 238716, 'C', 6631, 36),
 (7099, 960820, 234336, 'C', 4882, 48),
 (10063, 961013, 233424, 'C', 6484, 36),
 (5742, 950705, 232560, 'C', 4845, 48),
 (5724, 950419, 232560, 'C', 4845, 48),
 (10093, 940701, 231696, 'A', 6436, 36),
 (2699, 961225, 231168, 'C', 4816, 48),
 (378, 960722, 230400, 'C', 3840, 60),
 (8566, 931008, 230220, 'B', 6395, 36),
 (2262, 970208, 230220, 'C', 6395, 36),
 (9510, 960609, 228276, 'C', 6341, 36),
 (8982, 930925, 227880, 'A', 6330, 36),
 (9491, 960808, 225504, 'C', 4698, 48),
 (5628, 940617, 225420, 'C', 3757, 60),
 (8260, 930324, 224604, 'A', 6239, 36),
 (3189, 951129, 222180, 'D', 3703, 60),
 (5591, 960316, 221880, 'C', 3698, 60),
 (4413, 940115, 221280, 'C', 4610, 48),
 (8411, 941202, 220620, 'C', 3677, 60),
 (7713, 960525, 220440, 'C', 3674, 60),
 (8094, 961124, 220428, 'C', 6123, 36),
 (4784, 970808, 219456, 'C', 4572, 48),
 (10022, 970507, 218064, 'C', 4543, 48),
 (11042, 950129, 217152, 'A', 6032, 36),
 (808, 950613, 215616, 'D', 4492, 48),
 (10131, 931127, 215388, 'B', 5983, 36),
 (9179, 970121, 215040, 'C', 3584, 60),
 (2080, 970427, 214596, 'C', 5961, 36),
 (4852, 950413, 213300, 'C', 5925, 36),
 (11096, 961210, 213300, 'C', 3555, 60),
 (4144, 960819, 212976, 'C', 5916, 36),
 (6555, 930305, 212400, 'A', 5900, 36),
 (10005, 971129, 210744, 'C', 5854, 36),
 (525, 960320, 210384, 'C', 4383, 48),
 (5481, 930816, 209184, 'A', 4358, 48),
 (1876, 970920, 209040, 'C', 8710, 24),
 (10645, 961221, 208332, 'C', 5787, 36),
 (8051, 930207, 208320, 'A', 4340, 48),
 (790, 930511, 208128, 'B', 4336, 48),
 (3418, 960902, 207264, 'C', 4318, 48),
 (1978, 930611, 205200, 'A', 5700, 36),
 (4746, 970221, 204780, 'C', 3413, 60),
 (1011, 941217, 204000, 'C', 3400, 60),
 (7176, 961207, 203940, 'C', 3399, 60),
 (5362, 960906, 202848, 'C', 4226, 48),
 (1772, 950220, 202788, 'C', 5633, 36),
 (2456, 950909, 200976, 'C', 4187, 48),
 (2345, 931025, 199680, 'C', 3328, 60),
 (10630, 950115, 198240, 'A', 8260, 24),
 (10679, 970530, 197808, 'C', 8242, 24),
 (10940, 930913, 197748, 'A', 5493, 36),
 (472, 961011, 196800, 'D', 8200, 24),
 (10650, 970909, 196224, 'C', 4088, 48),
 (7769, 931003, 196080, 'A', 4085, 48),
 (10019, 950615, 194940, 'C', 5415, 36),
 (6924, 940601, 194880, 'C', 4060, 48),
 (10404, 961230, 194280, 'C', 3238, 60),
 (1580, 960108, 194256, 'C', 8094, 24),
 (7082, 960906, 194160, 'C', 4045, 48),
 (5256, 931025, 193968, 'A', 5388, 36),
 (4448, 930602, 192744, 'A', 5354, 36),
 (4447, 960616, 192744, 'C', 5354, 36),
 (1106, 930829, 192552, 'B', 8023, 24),
 (7606, 950315, 191880, 'C', 3198, 60),
 (9227, 971104, 191580, 'C', 3193, 60),
 (1528, 960608, 191088, 'C', 3981, 48),
 (1656, 970201, 189792, 'C', 3954, 48),
 (7824, 940517, 189696, 'B', 7904, 24),
 (7815, 950409, 189696, 'A', 7904, 24),
 (9093, 930616, 189300, 'C', 3155, 60),
 (960, 941102, 189060, 'C', 3151, 60),
 (9493, 950402, 188688, 'C', 3931, 48),
 (9353, 951103, 188616, 'C', 7859, 24),
 (1004, 960702, 188532, 'C', 5237, 36),
 (347, 931213, 187224, 'B', 7801, 24),
 (846, 960309, 187104, 'A', 7796, 24),
 (9006, 940902, 186384, 'C', 3883, 48),
 (8931, 960101, 186300, 'C', 3105, 60),
 (2228, 940319, 185952, 'C', 3874, 48),
 (8639, 970822, 185640, 'C', 3094, 60),
 (1318, 971222, 185544, 'C', 5154, 36),
 (5912, 961025, 184620, 'C', 3077, 60),
 (1250, 960328, 182640, 'C', 3805, 48),
 (11135, 931010, 182628, 'A', 5073, 36),
 (2218, 941121, 182040, 'C', 3034, 60),
 (6397, 950315, 181020, 'C', 3017, 60),
 (4981, 960122, 179328, 'C', 3736, 48),
 (873, 970426, 178500, 'C', 2975, 60),
 (5837, 960718, 177804, 'C', 4939, 36),
 (3166, 930810, 177744, 'D', 3703, 48),
 (5602, 960710, 177504, 'C', 3698, 48),
 (2035, 960510, 176328, 'C', 4898, 36),
 (9645, 960123, 176148, 'C', 4893, 36),
 (3562, 960719, 174960, 'C', 7290, 24),
 (3556, 970829, 174840, 'C', 2914, 60),
 (5428, 930414, 174744, 'B', 7281, 24),
 (5442, 930322, 174744, 'B', 7281, 24),
 (8533, 951010, 174048, 'C', 3626, 48),
 (5228, 930623, 173808, 'A', 7242, 24),
 (8547, 950717, 173016, 'C', 4806, 36),
 (1718, 970923, 172272, 'C', 7178, 24),
 (9104, 940121, 172080, 'A', 3585, 48),
 (5283, 970918, 170832, 'C', 3559, 48),
 (8713, 970518, 170700, 'C', 2845, 60),
 (7632, 960922, 170448, 'C', 3551, 48),
 (2167, 930808, 170256, 'A', 7094, 24),
 (11021, 930810, 168984, 'B', 7041, 24),
 (4725, 970414, 168264, 'C', 4674, 36),
 (10079, 930506, 167100, 'C', 2785, 60),
 (1801, 930213, 165960, 'A', 4610, 36),
 (67, 941019, 165960, 'A', 6915, 24),
 (1498, 970207, 165780, 'C', 2763, 60),
 (4999, 960212, 165168, 'C', 4588, 36),
 (2496, 940521, 165120, 'C', 2752, 60),
 (9225, 960101, 164256, 'C', 3422, 48),
 (4293, 960204, 164196, 'C', 4561, 36),
 (1527, 931117, 164052, 'B', 4557, 36),
 (9156, 970914, 163332, 'C', 4537, 36),
 (4681, 950808, 162624, 'C', 3388, 48),
 (110, 960717, 162576, 'C', 4516, 36),
 (1886, 960305, 162468, 'C', 4513, 36),
 (3608, 940830, 161496, 'C', 4486, 36),
 (276, 971208, 160920, 'C', 4470, 36),
 (7997, 960425, 160656, 'C', 6694, 24),
 (2350, 960804, 159744, 'C', 3328, 48),
 (4079, 931103, 158976, 'C', 3312, 48),
 (3629, 930727, 158760, 'C', 2646, 60),
 (5395, 960426, 158184, 'C', 4394, 36),
 (9560, 970713, 157068, 'C', 4363, 36),
 (2361, 940225, 156672, 'A', 4352, 36),
 (2728, 970706, 156420, 'C', 2607, 60),
 (785, 970809, 156096, 'C', 4336, 36),
 (8127, 941013, 155880, 'A', 6495, 24),
 (11244, 970112, 155760, 'C', 6490, 24),
 (7184, 950619, 155640, 'A', 6485, 24),
 (3021, 960420, 155616, 'C', 3242, 48),
 (9030, 950121, 155616, 'C', 3242, 48),
 (10728, 941223, 154656, 'C', 3222, 48),
 (10973, 930420, 154416, 'A', 3217, 48),
 (3875, 971018, 153936, 'C', 6414, 24),
 (7565, 960402, 153504, 'C', 3198, 48),
 (7894, 960409, 153144, 'C', 4254, 36),
 (10915, 970215, 152460, 'C', 2541, 60),
 (7240, 960423, 152160, 'C', 2536, 60),
 (9750, 940516, 151728, 'D', 3161, 48),
 (10439, 931121, 151560, 'A', 6315, 24),
 (4116, 971005, 151200, 'C', 4200, 36),
 (6461, 960717, 150912, 'C', 4192, 36),
 (4969, 960819, 150180, 'C', 2503, 60),
 (5385, 930521, 149340, 'C', 2489, 60),
 (1166, 930421, 149040, 'A', 3105, 48),
 (11054, 960201, 148920, 'C', 2482, 60),
 (1252, 950726, 148140, 'C', 4115, 36),
 (3353, 960827, 146064, 'C', 6086, 24),
 (7990, 960830, 144960, 'C', 3020, 48),
 (4937, 930220, 143904, 'A', 5996, 24),
 (1819, 961021, 143676, 'C', 3991, 36),
 (1698, 960314, 141948, 'C', 3943, 36),
 (4851, 960204, 141648, 'A', 5902, 24),
 (5952, 930907, 141240, 'A', 5885, 24),
 (5572, 970811, 140880, 'C', 2348, 60),
 (10812, 970408, 140688, 'C', 2931, 48),
 (3460, 970408, 140688, 'C', 2931, 48),
 (8041, 931010, 140400, 'A', 3900, 36),
 (7733, 960708, 140064, 'C', 5836, 24),
 (9656, 931114, 139536, 'A', 5814, 24),
 (6922, 970512, 139488, 'C', 5812, 24),
 (2236, 950827, 139464, 'D', 3874, 36),
 (4081, 950722, 137904, 'B', 5746, 24),
 (6715, 930915, 137880, 'D', 2298, 60),
 (10134, 970426, 136368, 'C', 5682, 24),
 (2622, 960821, 136344, 'C', 5681, 24),
 (4503, 950103, 135360, 'C', 2820, 48),
 (8316, 940604, 134784, 'A', 5616, 24),
 (9790, 951109, 133968, 'C', 2791, 48),
 (3907, 960418, 133848, 'C', 5577, 24),
 (10493, 970109, 133800, 'C', 5575, 24),
 (10911, 930529, 131292, 'A', 3647, 36),
 (3143, 961018, 130896, 'C', 5454, 24),
 (7594, 960216, 130464, 'C', 2718, 48),
 (11362, 951014, 129408, 'A', 5392, 24),
 (5267, 960112, 129312, 'D', 5388, 24),
 (4995, 940801, 128988, 'D', 3583, 36),
 (1242, 961124, 128544, 'C', 5356, 24),
 (8026, 970323, 128268, 'C', 3563, 36),
 (6699, 960608, 127200, 'C', 2650, 48),
 (9188, 930208, 127080, 'A', 2118, 60),
 (9828, 930520, 126600, 'A', 5275, 24),
 (1407, 970411, 125472, 'C', 5228, 24),
 (1389, 970805, 125472, 'C', 5228, 24),
 (8899, 940905, 125340, 'C', 2089, 60),
 (6856, 950819, 124344, 'C', 3454, 36),
 (290, 931202, 123696, 'A', 2577, 48),
 (5794, 950714, 123600, 'C', 2060, 60),
 (10411, 951123, 123408, 'A', 5142, 24),
 (1480, 960703, 123300, 'C', 3425, 36),
 (3112, 940812, 123216, 'C', 2567, 48),
 (9201, 961028, 122472, 'C', 5103, 24),
 (10105, 930428, 121896, 'A', 5079, 24),
 (9403, 930327, 120888, 'A', 3358, 36),
 (11069, 950602, 119136, 'C', 2482, 48),
 (5269, 960704, 117420, 'C', 1957, 60),
 (4894, 930620, 117024, 'A', 4876, 24),
 (9494, 960510, 116832, 'A', 9736, 12),
 (6686, 960210, 116496, 'C', 4854, 24),
 (9730, 970101, 116040, 'C', 1934, 60),
 (10738, 930417, 115992, 'A', 3222, 36),
 (10963, 950520, 115812, 'C', 3217, 36),
 (9731, 941201, 113796, 'A', 3161, 36),
 (10884, 950220, 113544, 'C', 3154, 36),
 (10243, 970903, 113436, 'C', 3151, 36),
 (303, 960725, 112752, 'C', 3132, 36),
 (2762, 930320, 111384, 'A', 4641, 24),
 (7437, 970808, 110736, 'C', 2307, 48),
 (38, 970808, 110736, 'C', 2307, 48),
 (6434, 950508, 110136, 'A', 4589, 24),
 (5001, 951215, 110112, 'A', 4588, 24),
 (226, 970223, 109344, 'C', 9112, 12),
 (993, 961114, 108720, 'C', 1812, 60),
 (11111, 930520, 108144, 'A', 3004, 36),
 (4727, 950213, 107640, 'A', 4485, 24),
 (3942, 960510, 107352, 'C', 2982, 36),
 (4660, 970103, 106944, 'C', 4456, 24),
 (4052, 970125, 106128, 'C', 2948, 36),
 (1843, 930130, 105804, 'A', 2939, 36),
 (6495, 960723, 104964, 'C', 8747, 12),
 (173, 931126, 104808, 'A', 8734, 12),
 (9591, 930520, 104712, 'A', 4363, 24),
 (9583, 940522, 104712, 'A', 4363, 24),
 (5700, 930720, 103680, 'D', 1728, 60),
 (97, 960505, 102876, 'A', 8573, 12),
 (675, 950803, 102240, 'C', 1704, 60),
 (2106, 960201, 101520, 'A', 8460, 12),
 (344, 931201, 100980, 'C', 1683, 60),
 (4127, 960503, 100800, 'D', 4200, 24),
 (6649, 950708, 100260, 'C', 1671, 60),
 (9017, 951122, 100224, 'D', 2088, 48),
 (4342, 960429, 100128, 'C', 4172, 24),
 (1447, 970220, 100080, 'C', 2085, 48),
 (9377, 950917, 99936, 'C', 4164, 24),
 (7180, 970612, 99744, 'C', 4156, 24),
 (1247, 930608, 99696, 'D', 2077, 48),
 (2343, 941209, 99336, 'A', 4139, 24),
 (8114, 951014, 99300, 'C', 1655, 60),
 (5698, 970904, 99216, 'C', 2756, 36),
 (4907, 940206, 98832, 'C', 2059, 48),
 (5650, 950108, 98592, 'A', 4108, 24),
 (11079, 951110, 98304, 'A', 8192, 12),
 (1012, 940709, 98184, 'A', 4091, 24),
 (8169, 951128, 97980, 'C', 1633, 60),
 (9833, 930724, 97632, 'A', 8136, 12),
 (7907, 960727, 97392, 'A', 8116, 12),
 (4414, 930910, 97224, 'A', 4051, 24),
 (4715, 961028, 97176, 'C', 4049, 24),
 (3916, 970928, 96984, 'C', 2694, 36),
 (6985, 950727, 96768, 'C', 2688, 36),
 (1787, 930322, 96396, 'B', 8033, 12),
 (9814, 950119, 96168, 'A', 8014, 12),
 (2419, 931127, 95808, 'A', 7984, 12),
 (6701, 930315, 95400, 'A', 2650, 36),
 (3273, 951229, 94512, 'B', 7876, 12),
 (7674, 960721, 94488, 'C', 3937, 24),
 (4473, 951009, 93960, 'C', 1566, 60),
 (2705, 930705, 93888, 'A', 2608, 36),
 (2720, 970616, 93888, 'C', 2608, 36),
 (8039, 951217, 93600, 'A', 3900, 24),
 (8523, 961125, 93036, 'C', 7753, 12),
 (2227, 940522, 92976, 'A', 3874, 24),
 (2116, 960502, 92400, 'A', 7700, 12),
 (2694, 930308, 91632, 'A', 7636, 12),
 (10049, 960328, 91632, 'A', 7636, 12),
 (7844, 931126, 91584, 'A', 3816, 24),
 (309, 970425, 91248, 'C', 1901, 48),
 (7485, 930728, 91200, 'A', 3800, 24),
 (544, 950515, 91152, 'A', 3798, 24),
 (5317, 961020, 90180, 'C', 2505, 36),
 (4361, 960311, 90156, 'A', 7513, 12),
 (11138, 950818, 89880, 'A', 3745, 24),
 (2580, 951109, 89340, 'C', 1489, 60),
 (9928, 951109, 89340, 'C', 1489, 60),
 (11231, 970205, 89280, 'A', 7440, 12),
 (8321, 930412, 89040, 'C', 1484, 60),
 (10351, 950504, 88704, 'C', 1848, 48),
 (2988, 961014, 88608, 'C', 7384, 12),
 (132, 960511, 88440, 'A', 7370, 12),
 (8772, 960516, 88272, 'C', 1839, 48),
 (9673, 970607, 88200, 'C', 2450, 36),
 (8261, 930512, 87840, 'A', 3660, 24),
 (4427, 930607, 87816, 'A', 7318, 12),
 (4631, 961212, 87528, 'C', 3647, 24),
 (6273, 930721, 87360, 'A', 3640, 24),
 (6265, 961101, 87360, 'C', 3640, 24),
 (5927, 931126, 87216, 'B', 1817, 48),
 (854, 930921, 87216, 'C', 1817, 48),
 (10361, 960621, 86880, 'A', 7240, 12),
 (9236, 930818, 86616, 'A', 7218, 12),
 (9422, 960306, 86184, 'A', 7182, 12),
 (2062, 960306, 86184, 'A', 7182, 12),
 (4467, 970413, 86184, 'C', 2394, 36),
 (8492, 940629, 85860, 'C', 1431, 60),
 (8680, 960212, 85716, 'C', 2381, 36),
 (6289, 950405, 85632, 'C', 1784, 48),
 (3967, 960922, 84600, 'D', 2350, 36),
 (4033, 961119, 84288, 'C', 1756, 48),
 (440, 961222, 84288, 'C', 1756, 48),
 (7926, 960609, 84120, 'A', 3505, 24),
 (9424, 961230, 83628, 'C', 2323, 36),
 (2064, 961230, 83628, 'C', 2323, 36),
 (9235, 950624, 83280, 'C', 1735, 48),
 (5622, 930208, 83016, 'A', 6918, 12),
 (3050, 930508, 82896, 'A', 6908, 12),
 (9208, 970524, 82128, 'C', 3422, 24),
 (4533, 970803, 81144, 'C', 2254, 36),
 (2, 930226, 80952, 'A', 3373, 24),
 (7401, 930226, 80952, 'A', 3373, 24),
 (8173, 930705, 80340, 'A', 6695, 12),
 (6353, 931126, 79920, 'C', 1332, 60),
 (5196, 970629, 79824, 'A', 6652, 12),
 (4259, 940408, 79632, 'A', 3318, 24),
 (5270, 930113, 79608, 'A', 3317, 24),
 (7890, 960326, 79344, 'C', 1653, 48),
 (1603, 930509, 78936, 'A', 6578, 12),
 (5944, 970606, 78720, 'C', 1640, 48),
 (5445, 970219, 78696, 'C', 2186, 36),
 (2165, 970408, 78600, 'C', 3275, 24),
 (10068, 970402, 77808, 'A', 6484, 12),
 (8027, 930707, 77640, 'A', 6470, 12),
 (7745, 961129, 77544, 'C', 2154, 36),
 (3230, 950311, 77184, 'C', 2144, 36),
 (6510, 961218, 76992, 'C', 3208, 24),
 (718, 960303, 76944, 'A', 6412, 12),
 (6473, 930126, 76908, 'B', 6409, 12),
 (8564, 930912, 76680, 'A', 3195, 24),
 (9640, 930313, 76416, 'A', 3184, 24),
 (3747, 940501, 76380, 'A', 6365, 12),
 (8919, 970703, 76104, 'C', 3171, 24),
 (4863, 960312, 76080, 'A', 6340, 12),
 (10266, 930610, 75624, 'B', 3151, 24),
 (3862, 961123, 74916, 'C', 2081, 36),
 (1270, 960607, 74772, 'C', 2077, 36),
 (8129, 930626, 74736, 'A', 2076, 36),
 (8519, 930402, 74688, 'A', 6224, 12),
 (8784, 961016, 74352, 'C', 3098, 24),
 (7136, 950409, 74124, 'C', 2059, 36),
 (4415, 950705, 74040, 'A', 6170, 12),
 (4423, 950426, 73836, 'A', 2051, 36),
 (7262, 960830, 73260, 'C', 1221, 60),
 (789, 950206, 73056, 'C', 1522, 48),
 (2247, 960413, 72504, 'C', 3021, 24),
 (6400, 951009, 72408, 'B', 3017, 24),
 (7859, 950314, 72120, 'A', 6010, 12),
 (9052, 950830, 71976, 'D', 2999, 24),
 (3403, 970520, 71820, 'C', 1995, 36),
 (7965, 931108, 71460, 'A', 5955, 12),
 (2143, 960113, 71460, 'C', 1985, 36),
 (1256, 940421, 71064, 'A', 1974, 36),
 (9024, 960105, 70656, 'C', 1472, 48),
 (2725, 970402, 69624, 'C', 1934, 36),
 (9159, 960802, 69600, 'C', 1450, 48),
 (11065, 930319, 69360, 'A', 1445, 48),
 (10762, 951023, 68832, 'C', 1912, 36),
 (3448, 960606, 68664, 'C', 2861, 24),
 (3754, 960219, 68544, 'A', 2856, 24),
 (1993, 941030, 68400, 'B', 5700, 12),

# DataSets

---

Dataset sobre las transacciones con Vyskov, extrayendo los años de las diferentes fechas.

In [ ]:
%%sql dataset << SELECT substr(a.date,0,3) acc_year, substr(t.date, 0, 3) year,amount, balance, k_symbol
FROM ACCOUNT a, TRANS t, DISTRICT d
WHERE a.district_id = d.A1 and d.A2 = "Vyskov"
AND a.account_id = t.account_id

 * sqlite:///data_berka.db
Done.
Returning data to local variable dataset

El data frame se lo observa en el lado izquierdo

In [ ]:
dataset.DataFrame().to_csv("dataset1.csv")